Movie space. Registration, login, profile and header buttons autotests
VK-BMSTU-QA/homework-selenium pull request #3
Opened 2022-11-27 19:36 UTC by nezhibitskiy

2022-11-29 21:51 UTC, mistergahan commented on hw/code/test_header.py
> +    # @pytest.mark.skip("SKIP")
убрать ненужные комменты

2022-11-29 21:52 UTC, mistergahan commented on hw/code/test_header.py
> +    # @pytest.mark.skip("SKIP")
убрать ненужные комменты

2022-11-29 21:52 UTC, mistergahan commented on hw/code/ui/pages/base_page.py
> +        # self.is_opened(self.url)
убрать ненужные комменты

2022-11-30 18:39 UTC, iiivan-lemon approved these changes

2022-12-01 08:43 UTC, vorolga approved these changes

2022-12-01 10:09 UTC, mistergahan approved these changes
Принял

2022-12-01 15:59 UTC, dkotegov requested changes
Надо убрать слипы
Прогнать pep8
Убрать бесполезные тесты, написать функциональные
Переделать все селекторы

2022-12-01 15:59 UTC, dkotegov commented on hw/code/ui/locators/basic_locators.py
> +    BUTTON_LOGOUT = (By.XPATH, '//*[@id="header"]/div[1]/div[5]/div/div[2]/a[3]')
Если какой-нибудь элемент в середине изменится или пропадет, то селектор упадет

2022-12-14 22:43 UTC, closed without merging