AKino (CoDex). Autotests. Selenium
VK-BMSTU-QA/homework-selenium pull request #4
Opened 2022-11-28 11:04 UTC by kalashkovpaul

AKino, команда CoDex
Виктор Киселёв - Регистрация. Авторизация. Футер
Антон Мужецкий - Страница одной подборки. Страница одного жанра. Страница поиска. Страница одной закладки
Константин Костинич - Страница подборок. Страница премьер. Страница жанров. Профиль. Шапка
Калашков Павел - Страница фильма. Страница фильма премьеры. Страница актёра

2022-11-28 12:24 UTC, Kislv commented
одобряю

2022-11-28 12:25 UTC, Kostich31 commented
Аппрув

2022-11-28 13:58 UTC, kalashkovpaul commented
Approve

2022-11-28 14:01 UTC, muzhts-anton commented
Аппрув

2022-11-30 15:00 UTC, alexey-ershkov requested changes
Отписал комментов, все комменты относятся ко всем тестам, просмотрите все комменты и посмотрите где вы что-то забыли у себя (даже если коммента нет)

2022-11-30 22:20 UTC, Kostich31 commented on hw/code/pageobjects/pages/profile.py
> +        return self.driver.find_element_by_xpath("//input[@value='Сохранить']")
Исправил

2022-11-30 22:20 UTC, Kostich31 commented on hw/code/pageobjects/base/page.py
> +    def btn_profile(self):
Вынес кнопки из базового класса

2022-11-30 22:21 UTC, Kostich31 commented on hw/code/tests/test_profile.py
> +# import pyautogui
Удалил

2022-11-30 22:24 UTC, Kostich31 commented on hw/code/tests/test_navbar.py
> +        self.page.btn_navbar_collections.click()
Разбил на несколько тестов

2022-11-30 22:24 UTC, Kostich31 commented on hw/code/tests/test_collections.py
> +        self.page.btn_navbar_collections.click()
Разбил

2022-11-30 22:25 UTC, Kostich31 commented on hw/code/tests/test_collections.py
> +        self.page.btn_navbar_genres.click()
Разбил

2022-11-30 22:34 UTC, Kostich31 commented on hw/code/pageobjects/pages/profile.py
> +        for i in List:
Убрал из страницы и переместил в тест

2022-11-30 22:34 UTC, Kostich31 commented on hw/code/pageobjects/pages/profile.py
> +    def bookmark_title(self, name):
убрал в тест

2022-11-30 22:34 UTC, Kostich31 commented on hw/code/pageobjects/base/page.py
> +    @property
убрал из базового класса

2022-12-01 02:55 UTC, Kislv commented on hw/code/pageobjects/pages/login.py
> +        # return self.driver.find_element(by=By.CLASS_NAME, value="github-hrefs")[1].text
выпилил

2022-12-01 02:55 UTC, Kislv commented on hw/code/pageobjects/pages/login.py
> +        # return self.driver.find_element(by=By.CLASS_NAME, value="github-hrefs")[1].text
выпилил

2022-12-01 02:57 UTC, Kislv commented on hw/code/pageobjects/pages/login.py
> +        return self.driver.find_element_by_link_text("Киселев Виктор")
Создал папку со всеми общими константами, использовал здесь константу оттуда

2022-12-01 02:57 UTC, Kislv commented on hw/code/pageobjects/pages/login.py
> +    def open(self, *args, **kwargs):
Опустил их

2022-12-01 02:58 UTC, Kislv commented on hw/code/pageobjects/pages/signup.py
> +        td_p_input = input.find_element_by_xpath('..')
Заменил на более понятное название

2022-12-01 02:58 UTC, Kislv commented on hw/code/tests/test_footer.py
> +        # self.assertEqual("https://github.com/Kislv/2022_1_CoDex", self.driver.current_url)
выпилил

2022-12-01 02:59 UTC, Kislv commented on hw/code/tests/test_login.py
> +        test_emails = ["a@2.r", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa6aaaaaaaaaaa@a.ru"]
вынес все эти значения в константы

2022-12-01 02:59 UTC, Kislv commented on hw/code/tests/test_login.py
> +        for i in test_emails:
изменил i на 'email'

2022-12-01 02:59 UTC, Kislv commented on hw/code/tests/test_login.py
> +        # test_passwords = ["1234abc", "12345aaaaa12345123456","12345678","qwertyui"]
убрал

2022-12-01 03:01 UTC, Kislv commented on hw/code/tests/test_signup.py
> +    # def test_signup_empty_error(self):
убрал

2022-12-01 10:36 UTC, kalashkovpaul commented on hw/code/pageobjects/pages/movie.py
> +        if rating < 1 or rating > 10:
Если вопрос стоит "Может ли быть тест, который намеренно вызывает эту функцию с значением меньше 1 или больше 10" - то нет
Но этой функцией могут пользоваться и вне этого модуля те, кто с ней не знакомы - могут случайно ошибиться, почему бы это не предусмотреть. Защитное программирование, все дела

2022-12-01 10:39 UTC, kalashkovpaul commented on hw/code/tests/test_movie.py
> +    def test_movie_add_to_collection_button(self):
Эти тесты проверяют наличие элементов, насколько могу судить по тому, что видел на работе, в таких тестах достаточно waitForVisible или чего-то такого - тест упадёт, если элемента не дождёмся

2022-12-01 13:52 UTC, alexey-ershkov requested changes

2022-12-01 13:52 UTC, alexey-ershkov commented on hw/code/pageobjects/base/page.py
> +
Перенос строки пж добавьте в конце

2022-12-01 13:52 UTC, alexey-ershkov commented on hw/code/pageobjects/base/paths/constants.py
> +    PINK_COLOR = "rgba(171, 35, 255, 1)"
и тут

2022-12-01 13:52 UTC, alexey-ershkov commented on hw/code/pageobjects/pages/bookmark.py
> +    # def __login(self, login, password):
а это нужно?

2022-12-01 13:52 UTC, alexey-ershkov commented on hw/code/pageobjects/pages/bookmark.py
> +        return WebDriverWait(self.driver, 1).until(ec.visibility_of_element_located((By.CLASS_NAME, bookmark_locator_paths.POPUP_CANCEL_BUTTON)))
вот такие повторяющиеся штуки можно вынести в базовый класс и закрыть за функцией, чтобы внутрь только локатор передавать

2022-12-01 13:52 UTC, alexey-ershkov commented on hw/code/pageobjects/pages/collections.py
> +        return self.driver.find_element(by=By.CLASS_NAME , value=collections_locator_paths.USER_BLOCK).find_element(by=By.CLASS_NAME, value=collections_locator_paths.BTN_LOGOUT)
чейнинг не оч читаем, давайте разбивать на несколько find_element

2022-12-01 13:52 UTC, alexey-ershkov commented on hw/code/pageobjects/pages/login.py
> +        # return self.driver.find_element(by=By.ID, value="email")
это кажется не нужно

2022-12-01 13:52 UTC, alexey-ershkov commented on hw/code/pageobjects/pages/movie.py
> +        if rating < 1 or rating > 10:
лучше выпилить, так как тесты под ваш проект, а то так нужно начинать во всех тестах валидировать входные данные

2022-12-01 13:52 UTC, alexey-ershkov commented on hw/code/pageobjects/pages/profile.py
> +        return self.driver.find_element(by=By.CLASS_NAME, value=profile_locator_paths.BTN_SINGLE_BOOKMARK)
вот эту страшную шутку тоже лучше в Page вынести и ток по локатор передавать

2022-12-01 13:52 UTC, alexey-ershkov commented on hw/code/pageobjects/pages/profile.py
> +        return WebDriverWait(self.driver, 10).until(ec.visibility_of_element_located((By.CLASS_NAME, profile_locator_paths.BTN_PROFILE)))
и вот такую длинную штуку тоже в Page

2022-12-01 13:52 UTC, alexey-ershkov commented on hw/code/tests/test_movie.py
> +        # self.loginPage.login("a@vk.ru", "1234abcd")
забыли выпилить кажется

2022-12-01 13:52 UTC, alexey-ershkov commented on hw/code/tests/test_movie.py
> +    def test_movie_add_to_collection_button(self):
лучше явно после ожидания написать assert с получением элемента без ожидания, а то не оч понятно, что именно в тесте проверяется

но твой поинт тоже валидный, если будет время добавь ассерты, если нет то переименуй тесты так, чтобы было понятно, что в них проверяется

2022-12-01 14:03 UTC, Kostich31 commented on hw/code/pageobjects/base/page.py
> +
добавил

2022-12-01 14:03 UTC, Kostich31 commented on hw/code/pageobjects/pages/bookmark.py
> +    # def __login(self, login, password):
убрано

2022-12-01 14:04 UTC, Kostich31 commented on hw/code/pageobjects/pages/login.py
> +        # return self.driver.find_element(by=By.ID, value="email")
убрал

2022-12-01 14:04 UTC, Kostich31 commented on hw/code/tests/test_movie.py
> +        # self.loginPage.login("a@vk.ru", "1234abcd")
убрал

2022-12-01 14:07 UTC, Kostich31 commented on hw/code/pageobjects/pages/collections.py
> +        return self.driver.find_element(by=By.CLASS_NAME , value=collections_locator_paths.USER_BLOCK).find_element(by=By.CLASS_NAME, value=collections_locator_paths.BTN_LOGOUT)
разбил на несколько

2022-12-01 14:44 UTC, alexey-ershkov commented
Аппрув

2022-12-14 23:22 UTC, closed without merging