VVT-i 3.0
VK-BMSTU-QA/homework-selenium pull request #7
Opened 2022-11-29 20:48 UTC by Natali-Skv

Скворцова Наталья https://github.com/VK-BMSTU-QA/homework-3/pull/13
Голубев Сергей https://github.com/VK-BMSTU-QA/homework-3/pull/12
Каташинский Кирилл https://github.com/VK-BMSTU-QA/homework-3/pull/14

2022-11-30 06:53 UTC, Natali-Skv commented
approved

2022-11-30 06:54 UTC, kirill555101 commented
approved

2022-11-30 07:46 UTC, yutfut commented
approved

2022-11-30 20:19 UTC, alexey-ershkov requested changes
Очень хорошая работа, лайк)  отписал комменты небольшие

2022-11-30 20:19 UTC, alexey-ershkov commented on hw/code/ui/components/cart_page.py
> +    def is_count_of_dish(self, count, number=1):
Проверку лучше делать в самом тесте в ассерте

2022-11-30 20:19 UTC, alexey-ershkov commented on hw/code/tests/test_card.py
> +        self.page.add_to_cart(1)
1 и 2 - магические числа, давайте их в константы

2022-11-30 20:19 UTC, alexey-ershkov commented on hw/code/tests/test_card.py
> +        assert self.page.is_count_of_dish("2", 2)
тут тоже какое-то магическое число

2022-11-30 20:19 UTC, alexey-ershkov commented on hw/code/ui/components/base_component.py
> +    def is_url(self, path):
Мб чуть более полно is_url_matches или около того, а то можно подумать, что просто проверка на то что передали является урлом и не более

2022-11-30 20:19 UTC, alexey-ershkov commented on hw/code/tests/test_login.py
> +        self.page.input_phone("+7(495")
давайте в константы или enum вынесем такие строки с понятными именами, чтобы было понятно, какой номер пытаетесь ввести (да, понятно что видно по названию теста, но если еще и в одноименной константе будет, то прям вообще конфетка)

2022-11-30 20:19 UTC, alexey-ershkov commented on hw/code/tests/test_profile.py
> +        self.page.send_new_name(" ")
давайте все строки в константы

2022-11-30 20:19 UTC, alexey-ershkov commented on hw/code/ui/components/base_component.py
> +    def is_invisible(self, locator, timeout=mini_timeout):
а точно ли нужно по таймауту тут ждать - кажется, что если вы хотите узнать видел элемент или нет, то можно сразу проверять - разве нет?

2022-11-30 20:19 UTC, alexey-ershkov commented on hw/code/ui/components/base_component.py
> +    def get_elem_text(self, locator, timeout=default_timeout):
и тут кажется это лишнее

по сути перед этим вам надо отдельно дождаться через wait_for_elem (вроде так у вас эта функция называется), что этот элемент есть, а в рамках этой функции сразу же брать значение

в общем в целом посмотрите на ваши утилитарные функции где вы по коду ожидаете чего-то, а по смыслу не должны. Это бьется на две более более простые операции - ожидание и получение

2022-11-30 20:19 UTC, alexey-ershkov commented on hw/code/ui/components/header.py
> +    def try_open_cart(self):
почему try? кажется что если нельзя открыть корзину, то это ошибка и тест должен упасть

2022-11-30 20:19 UTC, alexey-ershkov commented on hw/code/ui/components/login_page.py
> +        assert self.is_visible(self.locators.PROFILE_BUTTON)
а как assert закрался в страницу?

2022-11-30 20:19 UTC, alexey-ershkov commented on hw/code/ui/components/order_history_page.py
> +        self.wait_visability_of_elem(self.locators.ORDER_DETAILS)
кажется, что если get - то что-то должен возвращать

2022-11-30 20:19 UTC, alexey-ershkov commented on hw/code/ui/components/suggests_page.py
> +        self.click_after(self.locators.LAST_SUGGEST, 1)
магическая чиселка

2022-11-30 20:19 UTC, alexey-ershkov commented on hw/code/ui/fixtures.py
> +        # chrome_options.add_argument("--headless")
давайте либо раскомментим, либо уберем

2022-11-30 20:21 UTC, alexey-ershkov commented on README.md
> +sudo apt-get install python3-tk python3-dev
да и в целом стоит в ридми описать как запускать для человека у которого не стоит webdriver для хрома, откуда взять и как установить

2022-11-30 22:59 UTC, Natali-Skv commented on hw/code/ui/components/base_component.py
> +    def is_invisible(self, locator, timeout=mini_timeout):
эта функция предполагает работу с таймаутом.  
То есть мы проверяем элемент `invisible` сейчас или станет таковым в течении таймаута.     
Элементы не моментально переключают свойство видимости. Эта функция облегчает проверку условия переключения видимости, допуская определенную задержку

2022-11-30 23:14 UTC, Natali-Skv commented on hw/code/ui/components/header.py
> +    def try_open_cart(self):
эта функция используется для проверки:
> Открытие пустой корзины. При пустой корзине пользователя, при нажатии на элемент корзины ничего не происходит
  
*try* -- потому что мы не дожидаемся, когда корзина будет *visible*, как это происходит в функции *open_cart()*

2022-12-01 00:44 UTC, Natali-Skv commented on hw/code/ui/components/base_component.py
> +    def is_invisible(self, locator, timeout=mini_timeout):
она используется в `assert`.   
Если убрать таймаут, то как-то непонятно, что делать в такой ситуации:
- мы нажали на кнопку, которая вызывает исчезновение какого-то элемента
- мы хотим проверить, что этот элемент `invisible`

Для этого в любом случае всегда придется использовать wait именно для этого элемента, сразу проверять нельзя, мы можем опередить исчезновение элемента.   

Мне кажется это просто удобно, и не кидает исключения.

2022-12-01 06:32 UTC, Natali-Skv commented on hw/code/tests/test_login.py
> +        self.page.input_phone("+7(495")
По всему проекту постаралась вынести

2022-12-01 06:58 UTC, alexey-ershkov commented
Аппрув от ментора

2022-12-14 23:21 UTC, closed without merging